config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.urls import re_path as url
from django.views import defaults as default_views
from django.views.generic.base import RedirectView

urlpatterns = [
    path("", RedirectView.as_view(url="/feh/"), name="home"),
    # path(
    #    "about/",
    #    TemplateView.as_view(template_name="pages/about.html"),
    #    name="about",
    # ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    # path(
    #    "users/",
    #    include("linus.users.urls", namespace="users"),
    # ),
    url(r"^advanced_filters/", include("advanced_filters.urls")),
    path(
        "feh/",
        include("linus.feh.urls", namespace="feh"),
    ),
    # path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

linus/feh/urls.py
from django.urls import path
from django.urls import re_path as url
from django.views.decorators.cache import cache_page
from django.views.generic.base import TemplateView

from linus.feh.views import (
    CurlHeroes,
    CurlHeroesDoPhaseBase,
    HeroesList,
    HeroesListAjax,
    MaxOnlySkillsList,
    SkillsList,
    SkillsListAjax,
    SkillsListAjaxMax,
    lucksack_calculator,
)

from .views import aether_lift_calculator

app_name = "feh"
urlpatterns = [
    path("ar_calculator/", view=aether_lift_calculator, name="arcalc"),
    path("lucksack_calculator/", view=lucksack_calculator, name="lucksackcalc"),
    path("heroes/", view=cache_page(60 * 10)(HeroesList.as_view()), name="heroes_list"),
    path(
        "heroes_ajax.json",
        view=cache_page(60 * 10)(HeroesListAjax),
        name="heroes_list_ajax",
    ),
    path("curl_heroes/", CurlHeroes.as_view(), name="curl_heroes"),
    url(
        "^curl_heroes_do/(?P<phase>\d+)/(?P<password>[0-9a-fA-F]+)/$",
        view=cache_page(60)(CurlHeroesDoPhaseBase.as_view()),
        name="curl_heroes_do",
    ),
    path(
        "skills/",
        view=cache_page(60 * 10)(MaxOnlySkillsList.as_view()),
        name="skills_list",
    ),
    path(
        "max_skills_ajax.json",
        view=cache_page(60 * 10)(SkillsListAjaxMax),
        name="skills_list_max_ajax",
    ),
    path(
        "skills_ajax.json",
        view=cache_page(60 * 10)(SkillsListAjax),
        name="skills_list_ajax",
    ),
    path(
        "skills/all/",
        view=cache_page(60 * 10)(SkillsList.as_view()),
        name="skills_list_all",
    ),
    path(
        "",
        view=cache_page(60 * 10)(TemplateView.as_view(template_name="feh/welcome.html")),
        name="home",
    ),
]

linus/users/urls.py
from django.urls import path

from linus.users.views import user_detail_view, user_list_view, user_redirect_view, user_update_view

app_name = "users"
urlpatterns = [
    path("", view=user_list_view, name="list"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

linus/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = CharField(_("Name of User"), blank=True, max_length=255)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

linus/users/forms.py
from django.contrib.auth import forms, get_user_model
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

linus/feh/views.py
import sys
from datetime import date

from django.core.cache import cache
from django.core.exceptions import SuspiciousOperation
from django.http.response import JsonResponse
from django.shortcuts import redirect
from django.urls.base import reverse
from django.views.generic.base import RedirectView, TemplateView
from django.views.generic.edit import FormView

from linus.feh.lucksack_calc import FehSnipeProbability
from linus.feh.management.commands.curl_heroes import GetPklOutputFile
from linus.feh.models import AVAILABILITY, MOVEMENT_TYPE, WEAPON_TYPE
from linus.feh.poro import porocurler_v2
from linus.feh.poro.porocurler_v2 import CurlAll
from linus.feh.poro.poroparser_v2 import LoadPoro
from linus.feh.sliders import get_hero_stat_sliders, get_skill_stat_sliders

from . import forms, models
from .filters import (
    Filter,
    get_availability_filter,
    get_book_filter,
    get_f2p_filter,
    get_gender_filter,
    get_generation_filter,
    get_movement_permission_filter,
    get_movement_type_filter,
    get_origin_games_filter,
    get_season_filter,
    get_skill_slot_filter,
    get_stat_filter,
    get_true_false_filter,
    get_weapon_permission_filter,
    get_weapon_type_filter,
)

MULTIPLIER_MAX = 2


def AetherCost(lift):
    return min(50, (lift + 99) // 100 + 9)


def Pot(lift):
    return min(10, ((lift // 100) + 10) // 5)


def Calc(aether, lift, resets, lift_gain=100, aether_max=200, aether_regen=50):
    res = []
    current_aether = aether
    current_lift = lift
    res.append("Aether: {0}, Lift: {1}".format(current_aether, current_lift))

    pot_gains = []
    matches_multi = {}
    for i in range(1, MULTIPLIER_MAX + 1):
        matches_multi[i] = 0

    for x in range(resets + 1):
        res.append("")
        res.append("Start of day {0}/{1}".format(x, resets))
        if x:
            res.append("Aether regen daily.")
            current_aether += aether_regen
            res.append("Aether: {0}, Lift: {1}".format(current_aether, current_lift))
            current_aether = min(current_aether, aether_max)

        # Do Free Run
        # if has_free_run or x:
        #  pot_q = Pot(current_lift)
        #  res.append('>>>Free run. Pay 0. Get {0} from pots'.format(pot_q))
        #  current_aether += pot_q
        #  current_aether = min(current_aether, aether_max)
        #  current_lift += lift_gain
        #  pot_gains.append(pot_q)
        #  res.append('Aether: {0}, Lift: {1}'.format(current_aether, current_lift))

        # Do double runs as much as you can, except last day.
        while current_aether >= AetherCost(current_lift):
            if x < resets and current_aether + aether_regen <= aether_max:
                # be lazy and do it later.
                break

            cost = AetherCost(current_lift)
            pot = Pot(current_lift)
            multiplier = 1
            if cost * 2 <= current_aether:
                # do dubble match.
                multiplier = 2

            res.append(
                ">>>{2}x run. Pay {0}. Get {1} from pots".format(cost * multiplier, pot * multiplier, multiplier)
            )

            matches_multi[multiplier] += 1

            current_aether -= cost * multiplier
            current_aether += pot * multiplier
            for _ in range(multiplier):
                pot_gains.append(pot)
            current_aether = min(current_aether, aether_max)
            current_lift += lift_gain * multiplier
            res.append("Aether: {0}, Lift: {1}".format(current_aether, current_lift))

    # How many pots can I miss?
    can_miss = 0
    if len(pot_gains) >= 2:
        spare = current_aether - pot_gains[-1]
        i = len(pot_gains) - 2
        while i >= 0:
            if spare - pot_gains[i] >= 0:
                spare -= pot_gains[i]
                can_miss += 2
                i -= 1
            elif spare - (pot_gains[i] - pot_gains[i] / 2) >= 0:
                spare -= pot_gains[i] - pot_gains[i] / 2
                can_miss += 1
                break
            else:
                break

    return res, current_aether, current_lift, can_miss, matches_multi


class AetherLiftCalculator(FormView):
    template_name = "feh/calculator.html"
    form_class = forms.AetherLiftForm
    res = ""

    def get_context_data(self, *args, **kwargs):
        context = FormView.get_context_data(self, *args, **kwargs)
        context["res"] = self.res
        return context

    def form_valid(self, form):
        log, aether, lift, can_miss, matches = Calc(
            form.cleaned_data["aether"],
            form.cleaned_data["lift"],
            form.cleaned_data["reset_left"],
            form.cleaned_data["lift_gain"],
            form.cleaned_data["aether_storage_max"],
            form.cleaned_data["aether_regen"],
        )
        matches_keys = matches.keys()
        matches_result = []
        for match_key in sorted(matches_keys):
            matches_result.append(dict(multiplier=match_key, num=matches[match_key]))
        self.res = dict(
            log="\n".join(log),
            aether=aether,
            lift=lift,
            can_miss=can_miss,
            matches=sum(matches.values()),
            breakdown=matches_result,
        )
        return self.get(form)


aether_lift_calculator = AetherLiftCalculator.as_view()


class LucksackCalculator(FormView):
    template_name = "feh/lucksack.html"
    form_class = forms.LucksackForm
    res = ""

    def get_context_data(self, *args, **kwargs):
        context = FormView.get_context_data(self, *args, **kwargs)
        context["res"] = self.res
        return context

    def form_valid(self, form):
        orbs = form.cleaned_data.get("orbs")

        ssr_focus = form.cleaned_data.get("five_star_focus_chance_total")
        ssr_pity = form.cleaned_data.get("five_star_pitybreaker_chance_total")

        ssr_f_sc = form.cleaned_data.get("number_of_other_focus_units_with_the_same_color_as_target")
        ssr_f_wc = form.cleaned_data.get("number_of_other_focus_units_with_different_color_than_target")

        ssr_n_sc = form.cleaned_data.get("number_of_five_star_units_with_the_same_color_as_target")
        ssr_n_wc = form.cleaned_data.get("number_of_five_star_units_with_different_color_than_target")

        com_n_sc = form.cleaned_data.get("number_of_four_star_or_lower_units_with_the_same_color_as_target")
        com_n_wc = form.cleaned_data.get("number_of_four_star_or_lower_units_with_different_color_than_target")

        already_in_pool = form.cleaned_data.get("is_target_unit_already_in_summonable_pool")

        total_focus_units = 1 + ssr_f_sc + ssr_f_wc
        total_ssr_units = ssr_n_sc + ssr_n_wc
        total_com_units = com_n_sc + com_n_wc

        units = [
            (1, "red", 1, ssr_focus / total_focus_units),
            (2, "red", 1, ssr_f_sc * ssr_focus / total_focus_units),
            (3, "blue", 1, ssr_f_wc * ssr_focus / total_focus_units),
            # (4, 'red', 1, ssr_n_sc * ssr_pity / total_ssr_units),
            (5, "blue", 1, ssr_n_wc * ssr_pity / total_ssr_units),
            (6, "red", 0, com_n_sc * (1.0 - ssr_focus - ssr_pity) / total_com_units),
            (7, "blue", 0, com_n_wc * (1.0 - ssr_focus - ssr_pity) / total_com_units),
        ]
        if already_in_pool:
            units.append((1, "red", 1, ssr_pity / total_ssr_units))
            units.append((4, "red", 1, (ssr_n_sc - 1) * ssr_pity / total_ssr_units))
        else:
            units.append((4, "red", 1, ssr_n_sc * ssr_pity / total_ssr_units))

        sys.setrecursionlimit(10000)
        sackchance = FehSnipeProbability(orbs, units, 1)
        self.res = list(enumerate(sackchance))

        return self.get(form)


lucksack_calculator = LucksackCalculator.as_view()


def GetRandomAxeInfantry():
    return (
        models.Hero.objects.filter(
            weapon_type=WEAPON_TYPE.G_AXE,
            movement_type=MOVEMENT_TYPE.INFANTRY,
            availability=AVAILABILITY.STANDARD,
        )
        .exclude(name="Linus")
        .order_by("?")[0]
    )


def GetRandomUnit():
    return models.Hero.objects.all().order_by("?")[0]


def HeroesListAjax(request):
    heroes = list(models.Hero.objects.all().order_by("name", "title"))
    data = []
    for hero in heroes:
        herodata = {}
        herodata["full_name"] = dict(
            name=hero.name,
            title=hero.title,
            full_name=hero.full_name,
            icon=hero.availability_icon,
            human=hero.availability_human,
            url=hero.gamepedia_url,
            # hero_icon_url=hero.icon_image.url, #TODO: more work than seems ot get it back
        )
        herodata["f2p_level"] = dict(
            name=hero.f2p_level,
            icon=hero.f2p_level_icon,
            title=hero.f2p_level_human,
        )
        herodata["weapon_type"] = dict(
            name=hero.weapon_type,
            icon=hero.weapon_type_icon,
            title=hero.weapon_type_human,
        )
        herodata["movement_type"] = dict(
            name=hero.movement_type,
            icon=hero.movement_type_icon,
            title=hero.movement_type_human,
        )

        herodata["boonbanes"] = hero.boonbanes

        pairs = [
            (hero.stats(), "stats"),
            (hero.max_stats, "max_stats"),
            (hero.adjusted_stats, "adjusted_stats"),
        ]
        for attrib, atname in pairs:
            ctxl = []
            for i in range(len(attrib)):
                ctxl.append(dict(value=attrib[i], bb=hero.boonbanes[i]))
            herodata[atname] = ctxl

        herodata["bst"] = hero.bst
        herodata["max_bst"] = hero.max_bst
        herodata["adjusted_bst"] = hero.adjusted_bst

        herodata["generation"] = hero.generation
        herodata["release_date"] = dict(
            display=hero.release_date.strftime("%-d %b %Y"),
            sortplay=hero.release_date.strftime("%Y-%m-%d"),
        )

        # herodata['weapon_type'] = hero.weapon_type

linus/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserListView(LoginRequiredMixin, ListView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_list_view = UserListView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

linus/templates/feh/calculator.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}AR Calculator{% endblock %}

{% block content %}
  <h1>AR Max Lift Calculator</h1>

  <div class='row'>
    <div class='col-md-4'>
      <form class="form-horizontal" method="post" action="{% url 'feh:arcalc' %}">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="control-group">
          <div class="controls">
            <button type="submit" class="btn">Go!</button>
          </div>
        </div>
      </form>
    </div>
    <div class='col-md-8'>
      {% if res %}
        <table class="table table-striped">
          <tbody>
            <tr>
              <td>Max Lift</td>
              <td>{{ res.lift }}</td>
            </tr>
            <tr>
              <td>Remaining Aether</td>
              <td>{{ res.aether }}</td>
            </tr>
            <tr>
              <td>Total matches</td>
              <td>{{ res.matches }}</td>
            </tr>
            {% for match in res.breakdown %}
              <tr>
                <td>Number of {{ match.multiplier }}x matches</td>
                <td>{{ match.num }}</td>
              </tr>
            {% endfor %}
            <tr>
              <td>Max pots missed<br/>(excluding last match, assuming all runs are 1x multiplier)</td>
              <td>{{ res.can_miss }}</td>
            </tr>
          </tbody>
        </table>
      {% endif %}
    </div>
  </div>

  <p>
    <div class="card card-body bg-light">
      {% if res %}
  <pre><code>Full output log:

{{ res.log }}</code></pre>
      {% endif %}
    </div>
  </p>
{% endblock %}

linus/templates/feh/heroes.html
{% extends "feh/kannadb_base.html" %}

{% load static %}

{% block title %}Heroes{% endblock %}

{% block javascript %}
  {{ block.super }}
  <script src="{% static 'js/heroes_2.js' %}?v=1"></script>
{% endblock %}

{% block kannadbsidebar %}
  {% include "feh/sidebar.html" %}
{% endblock %}

{% block kannadbmain %}

  <h3>Heroes</h3>

  <div class="toggles-container">
    <div class="toggles-title">
      Toggle column:
    </div>
    <div class="toggles">
      <a class="toggle-vis" data-column="0">Name</a>
      <a class="toggle-vis" data-column="1">F2P</a>
      <a class="toggle-vis" data-column="2">Weapon</a>
      <a class="toggle-vis" data-column="3">Movement</a>
      <a class="toggle-vis" data-column="22">Generation</a>
      <a class="toggle-vis" data-column="23">Release Date</a>
      <a class="toggle-vis" data-column="27">Book</a>
      <a class="toggle-vis" data-column="30">Skills</a>
      <a class="toggle-vis" data-column="31">Game</a>
      <a class="toggle-vis" data-column="33">Gender</a>
      <a class="toggle-vis" data-column="34">Is Dancer</a>
      <a class="toggle-vis" data-column="35">MinMax Rating</a>
      <a class="toggle-vis" data-column="36">Source</a>
      <a class="toggle-vis" data-column="37">Resplendent</a>
      <a class="toggle-vis" data-column="38">Season</a>
      <a class="toggle-vis" data-column="39">Duo/Harmo Skill</a>
      <a class="toggle-vis" data-column="40">Artist</a>
      <a class="toggle-vis" data-column="42">Dragonflowers</a>
    </div>
  </div>

  <table id='heroes-table' class='table table-striped' width="100%">
    <thead>
      <tr>
        <td>Name</td>
        <td><small>F2P</small></td>
        <td>Wp</td>
        <td>Mv</td>
        <td><small>HP</small></td>
        <td><small>Atk</small></td>
        <td><small>Spd</small></td>
        <td><small>Def</small></td>
        <td><small>Res</small></td>
        <td><small>BST</small></td>

        <td><small>HP</small></td>
        <td><small>Atk</small></td>
        <td><small>Spd</small></td>
        <td><small>Def</small></td>
        <td><small>Res</small></td>
        <td><small>BST</small></td>

        <td><small>HP</small></td>
        <td><small>Atk</small></td>
        <td><small>Spd</small></td>
        <td><small>Def</small></td>
        <td><small>Res</small></td>
        <td><small>BST</small></td>

        <td>Gen</td>
        <td>Release</td>
        <td>Weapon Type</td>
        <td>Movement Type</td>

        <td>F2P</td>
        <td>Book</td>
        <td>Generation</td>
        <td>Availability</td>
        <td>Skills</td>
        <td>Game</td>
        <td>Stripped Name</td>
        <td>Gender</td>
        <td>Dancer</td>
        <td>MinMax</td>

        <td>Source</td>
        <td>Resplendent</td>
        <td>Season</td>
        <td>Harmonized Skill</td>
        <td>Artist</td>

        <td>Alias</td>
        <td>Dragonflowers</td>
      </tr>
    </thead>
    <tbody>
    </tbody>
  </table>

{% endblock %}

linus/templates/feh/kannadb_base.html
{% extends "base.html" %}

{% load static %}

{% block javascript %}
  {{ block.super }}
  <script src="https://unpkg.com/@popperjs/core@2"></script>
  <script src="https://unpkg.com/tippy.js@6"></script>
  <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

  <!-- Popper.JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
  <!-- Bootstrap JS -->
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>

  <script src="{% static 'js/project.js' %}"></script>
{% endblock %}

{% block css %}
  {{ block.super }}

  <!-- Pace loading progress-->
  <script src="{% static 'lib/pace/js/pace.min.js' %}"></script>
  <!-- <link rel="stylesheet" type="text/css" href="{% static 'css/modern-art.css' %}"> -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/loading-bar.css' %}">

  <!--<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.css">-->
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css">
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

  <!-- Font Awesome JS -->
  <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
  <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>

  <link rel="stylesheet" type="text/css" href="{% static 'css/heroes_2.css' %}">
{% endblock %}

{% block overridecontent %}
  <div class="full-wrapper">
    <div class="header">
      <button type="button" id="sidebarCollapse" class="btn btn-primary">
        <i class="fas fa-align-left"></i>
      </button>
      <a class="header-logo" href="{% url 'feh:home' %}">
        <div class="header-title">
          <img class="header-image" src="{% static 'images/icons/kannadb.png' %}">
          KannaDB
        </div>
      </a>

      <!-- DB Links in the Header -->
      <div class="header-links">
        <a href="{% url 'feh:heroes_list' %}" class="header-link">HeroesDB</a>
        <a href="{% url 'feh:skills_list' %}" class="header-link">SkillsDB (max)</a>
        <a href="{% url 'feh:skills_list_all' %}" class="header-link">SkillsDB (all)</a>
      </div>

      <div class="header-credits">
        <small>
          Made by LinusMain and Pororo, revived by Avestus
        </small>
      </div>
      <button id="darkModeToggle" class="dark-mode-btn btn btn-sm">Toggle Dark Mode</button>
    </div>
    <div class="content-wrapper">
      <nav id="sidebar">
        {% block kannadbsidebar %}
        {% endblock %}
      </nav>

      <!-- Page Content -->
      <div id="content">
        {% block kannadbmain %}
        {% endblock %}
      </div>
    </div>
  </div>
{% endblock %}

{% block extrajs %}
  <script src="{% static 'js/content_common.js' %}"></script>
{% endblock %}

linus/templates/feh/lucksack.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Lucksack Calculator{% endblock %}

{% block content %}
  <h1>HOW LUCKSACK ARE YOU?</h1>

  <div class='row'>
    <div class='col-md-4'>
      <form class="form-horizontal" method="post" action="{% url 'feh:lucksackcalc' %}">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="control-group">
          <div class="controls">
            <button type="submit" class="btn">Go!</button>
          </div>
        </div>
      </form>
    </div>
    <div class='col-md-8'>
      {% if res %}
        <table class="table table-striped">
          <tbody>
            <tr>
              <td>Number of units</td>
              <td>Chance</td>
            </tr>
            {% for i in res %}
              <tr>
                <td>{{ i.0 }}</td>
                <td>{{ i.1 }}</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      {% endif %}
    </div>
  </div>

{% endblock %}

linus/templates/feh/welcome.html
{% extends "base.html" %}

{% load static %}

{% block title %}KannaDB FEH Database{% endblock %}

{% block content %}
  <h1 class='text-center'>KannaDB: Fire Emblem Heroes (FEH) Database, Search, and Filter</h1>
  <p class='text-center'>
    <img height="40pt" src="{% static 'images/icons/kannadb.png' %}">
    Moshi moshi, this is Kanna speaking.
    <img height="40pt" src="{% static 'images/icons/kannadb.png' %}">
  </p>

  <a class='btn btn-primary btn-block' href='{% url "feh:heroes_list" %}'>
    Heroes DB</a>
  <a class='btn btn-success btn-block' href='{% url "feh:skills_list" %}'>
    Skills DB (Max Skills Only)</a>
  <a class='btn btn-warning btn-block' href='{% url "feh:arcalc" %}'>
    AR Lift Calculator</a>
  <a class='btn btn-danger btn-block' href='{% url "feh:skills_list_all" %}'>
    Skills DB (All Skills)</a>

  <a class='btn btn-info btn-block' href='http://www.arcticsilverfox.com/score_calc/'>
    Arena Score Calculator (by ASFox)
  </a>

  <a class='btn btn-info btn-block' href='http://www.arcticsilverfox.com/feh_sim/'>
    FEH Mass Duel Simulator (by ASFox)
  </a>

  <p>Made by LinusMain and Pororo, revived by Avestus. Data sourced from Gamepedia.</p>
{% endblock %}